#print("Hello World!\nRavi Dubey")
#print("Hello" +" Ravi Dubey")
#print("Hello" +" " + "Ravi Dubey")
#print("Hello " + input("What is your name? "))
#print("Welcome to the Band Name Generator")
#city_name= input("What's Name of the city you grew up in?\n")
#pet_name= input("What's your pet's name\n")
#print("Your band name could be "+city_name + " " +pet_name)
#print("Ravi Dubey"[0])
your_name = input("Enter Name: ")
name_length = len(your_name)
print(name_length)
last_number = name_length -1
print(your_name[last_number])
print(your_name[name_length-2])